### ISSUE TITLE
Update documentation with info about custom types

### ISSUE THREAD

**Issue by Lexinek** [nettrine/dbal#5]
Please add example of at least one custom type registered via config.

As i found in ConnectionFactory - https://github.com/nettrine/dbal/blob/master/src/ConnectionFactory.php#L121 from code it seems that syntax is following:
```
types:
    myType: {class: MyTypeClass}
// same as
    myType:
        class: MyTypeClass
```

Is that correct?

**Comment by f3l1x** [comment]
Resolved in 5c82fc658df71ac637a7f8796d4ea6a914bd7be0.
Related: #6 
----

```
dbal:
    connection:
        types:
            uuid_binary_ordered_time:
                class: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
                commented: false
```

**Comment by JanMikes** [comment]
@f3l1x is there any way that we could write

```yml
types:
    MyTypeName: MyTypeClass
```

instead of
```yml
types:
    MyTypeName:
                class: MyTypeClass
                commented: false
```


I have class like this:
```php
final class EmailAddressType extends StringType
{
	public function convertToPHPValue($value, AbstractPlatform $platform)
	{
		\assert(is_string($value));

		return EmailAddress::fromString($value);
	}


	public function convertToDatabaseValue($value, AbstractPlatform $platform)
	{
		\assert($value instanceof EmailAddress);

		return parent::convertToDatabaseValue($value->toString(), $platform);
	}


	public function requiresSQLCommentHint(AbstractPlatform $platform): bool
	{
		return true;
	}


	public function getName(): string
	{
		return EmailAddress::class;
	}
}
```

Does it mean that `getName()` and `requiresSQLCommentHint()` methods are unused? It seems to me that it is overhead. Just thinking if it could be improved somehow.

Anyways i was thinking if it is possible to create extension which would autoregister all custom types, do you think something like that is possible? If yes i might try that and send PR to this repo, i think it would be awesome.
