### ISSUE TITLE
Error during adding new type

### ISSUE THREAD

**Issue by f3l1x** [nettrine/dbal#6]
```
connection:
            host: db
            user: ::getenv('MYSQL_USER')
            password: ::getenv('MYSQL_ROOT_PASSWORD')
            dbname: ::getenv('MYSQL_DATABASE')
            driver: pdo_mysql
            types:
                uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
```

![download](https://user-images.githubusercontent.com/538058/38247664-650dddac-3746-11e8-8ff7-766c08585c3e.png)

**Comment by f3l1x** [comment]
Working example.

```
connection:
            types:
                uuid_binary_ordered_time:
                    class: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
                    commented: false
```
